spring.application.name=PlayWallServer

server.port=10023

logging.level.de.tobias.playwall=DEBUG

de.tobias.playwall.path-provider.base-directory-template={appdata}/PlayWall/de.tobias.playwall.server.v8