#!/usr/bin/env node
// Regenerates src/version.generated.ts from package.json's "version". Maven sets that version to the PlayWall
// version right before packaging (see pom.xml), so the packaged module knows which server version it matches —
// package.json itself is not part of the packaged runtime, hence the version is baked into the build.
// Run via "npm run sync-version", or automatically as part of "npm run build"/"npm run dev".

import {readFileSync, writeFileSync} from 'node:fs'
import {dirname, relative, resolve} from 'node:path'
import {fileURLToPath} from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const {version} = JSON.parse(readFileSync(resolve(here, '../package.json'), 'utf8'))
const outputPath = resolve(here, '../src/version.generated.ts')

writeFileSync(outputPath, `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit by hand.
// Regenerate with "npm run sync-version" (also runs automatically as part of "npm run build"/"npm run dev").

export const MODULE_VERSION = '${version}'
`)
console.log(`Wrote version ${version} to ${relative(process.cwd(), outputPath)}`)
