name: "PlayWall"
version: "@project.version@"
build: @project.build.code@
identifier: "de.tobias.playwall.v8"
date: "@project.versionDate@"

main: "de.tobias.playwall.client.PlayWallMain"
author: "Tobias Ullerich, Robert Goldmann"

basePath: "PlayWall"

serverBaseURL: "https://playwall.thecodelabs.de/files"

userInfo:
  website: "https://playwall.thecodelabs.de/"
  repository: "https://thecodelabs.de/PlayWall/PlayWall"
