[package]
name = "PlayWallNativeAudioRust"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
jni = "0.21.1"
rodio = { version = "0.21.1", features = ["mp3"] }
symphonia = "0.5.4"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

[lib]
crate-type = ["cdylib"]
