<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>de.tobias.playwall</groupId>
        <artifactId>PlayWall</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>PlayWallNativeAudioRust</artifactId>
    <packaging>pom</packaging>

    <properties>
        <sonar.sources>src</sonar.sources>
        <sonar.exclusions>target/**</sonar.exclusions>
    </properties>

    <profiles>
        <profile>
            <id>build-rust</id>
            <activation>
                <os>
                    <family>mac</family>
                </os>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>build-rust</id>
                                <phase>generate-resources</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>cargo</executable>
                                    <arguments>
                                        <argument>build</argument>
                                        <argument>--release</argument>
                                    </arguments>
                                    <workingDirectory>${project.basedir}</workingDirectory>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-resources-plugin</artifactId>
                        <version>${maven-resources-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>copy-rust-lib</id>
                                <phase>process-resources</phase>
                                <goals>
                                    <goal>copy-resources</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.basedir}/../PlayWallNativeAudio/src/main/resources/rust</outputDirectory>
                                    <resources>
                                        <resource>
                                            <directory>${project.basedir}/target/release</directory>
                                            <includes>
                                                <include>*.dll</include>
                                                <include>*.so</include>
                                                <include>*.dylib</include>
                                            </includes>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>sign-rust</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>sign-dylib</id>
                                <phase>process-resources</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>codesign</executable>
                                    <arguments>
                                        <argument>--force</argument>
                                        <argument>--options</argument>
                                        <argument>runtime</argument>
                                        <argument>--timestamp</argument>
                                        <argument>--keychain</argument>
                                        <argument>${mac.sign.keychain}</argument>
                                        <argument>--sign</argument>
                                        <argument>${mac.sign.identity}</argument>
                                        <argument>libPlayWallNativeAudioRust.dylib</argument>
                                    </arguments>
                                    <workingDirectory>${project.basedir}/target/release</workingDirectory>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>