<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.tobias.playwall</groupId>
        <artifactId>PlayWall</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>PlayWallClient</artifactId>

    <properties>
        <surefire.argLineBase>
            --add-opens=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED
            --enable-native-access=javafx.graphics
            -javaagent:${settings.localRepository}/org/mockito/mockito-core/${mockito.version}/mockito-core-${mockito.version}.jar
        </surefire.argLineBase>
        <surefire.argLine>${surefire.argLineBase}</surefire.argLine>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-swing</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.controlsfx</groupId>
            <artifactId>controlsfx</artifactId>
            <version>${controlsfx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.github.classgraph</groupId>
            <artifactId>classgraph</artifactId>
            <version>${classgraph.version}</version>
        </dependency>

        <dependency>
            <groupId>de.thecodelabs</groupId>
            <artifactId>libUtils</artifactId>
        </dependency>
        <dependency>
            <groupId>de.thecodelabs</groupId>
            <artifactId>libLogger</artifactId>
        </dependency>
        <dependency>
            <groupId>de.thecodelabs</groupId>
            <artifactId>libJfx</artifactId>
        </dependency>
        <dependency>
            <groupId>de.tobias.playwall</groupId>
            <artifactId>PlayWallCommon</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>testfx-core</artifactId>
            <version>${testfx-core.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>testfx-junit5</artifactId>
            <version>${testfx-core.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${mockito.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>openjfx-monocle</artifactId>
            <version>${openjfx-monocle.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <excludes>
                    <exclude>config/</exclude>
                </excludes>
            </resource>
            <resource>
                <directory>src/main/resources/config</directory>
                <filtering>true</filtering>
                <targetPath>${project.build.outputDirectory}/config</targetPath>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>nl.geodienstencentrum.maven</groupId>
                <artifactId>sass-maven-plugin</artifactId>
                <version>${sass-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>translate-css</id>
                        <goals>
                            <goal>update-stylesheets</goal>
                        </goals>
                        <phase>generate-resources</phase>
                        <configuration>
                            <destination>target/classes/style</destination>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${maven-jar-plugin.version}</version>
                <configuration>
                    <outputDirectory>${project.build.directory}/build</outputDirectory>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>${surefire.argLine}</argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>headless-ui-tests</id>
            <properties>
                <surefire.argLine>
                    ${surefire.argLineBase}
                    --add-opens=javafx.graphics/com.sun.javafx.util=ALL-UNNAMED
                    --add-opens=javafx.base/com.sun.javafx.logging=ALL-UNNAMED
                    -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw
                </surefire.argLine>
            </properties>
        </profile>

        <profile>
            <id>code-coverage</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <argLine>${surefire.argLine} ${surefire.argLineJacoco}</argLine>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>windows</id>
            <activation>
                <os>
                    <family>Windows</family>
                </os>
            </activation>
            <properties>
                <app.icon>src/main/resources/de/tobias/playwall/client/logo/icon.ico</app.icon>
                <installer.extension>exe</installer.extension>
            </properties>
        </profile>

        <!-- macOS Build -->
        <profile>
            <id>mac</id>
            <activation>
                <os>
                    <family>mac</family>
                </os>
            </activation>
            <properties>
                <app.icon>src/main/resources/de/tobias/playwall/client/logo/icon.icns</app.icon>
                <installer.extension>dmg</installer.extension>
            </properties>
        </profile>

        <profile>
            <id>package-executables</id>

            <dependencies>
                <dependency>
                    <groupId>org.fusesource.jansi</groupId>
                    <artifactId>jansi</artifactId>
                    <version>2.4.0-module</version>
                </dependency>
                <dependency>
                    <groupId>net.java.dev.jna</groupId>
                    <artifactId>jna</artifactId>
                    <version>5.11.0-module</version>
                </dependency>
                <dependency>
                    <groupId>net.java.dev.jna</groupId>
                    <artifactId>jna-platform</artifactId>
                    <version>5.11.0-module</version>
                </dependency>
            </dependencies>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.openjfx</groupId>
                        <artifactId>javafx-maven-plugin</artifactId>
                        <version>${javafx-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>create-runtime-image</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>jlink</goal>
                                </goals>
                                <configuration>
                                    <mainClass>de.tobias.playwall.client.PlayWallMain</mainClass>
                                    <stripDebug>true</stripDebug>
                                    <compress>2</compress>
                                    <noHeaderFiles>true</noHeaderFiles>
                                    <noManPages>true</noManPages>
                                    <launcher>PlayWall</launcher>
                                    <jlinkImageName>PlayWallClient</jlinkImageName>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.gmaven</groupId>
                        <artifactId>groovy-maven-plugin</artifactId>
                        <version>${groovy-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>generate-uuid</id>
                                <phase>initialize</phase>
                                <goals>
                                    <goal>execute</goal>
                                </goals>
                                <configuration>
                                    <source>
                                        import java.util.UUID

                                        project.properties.setProperty("win.upgrade.uuid", UUID.randomUUID().toString())
                                    </source>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                        <version>${jpackage-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>build-executable</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>jpackage</goal>
                                </goals>
                                <configuration>
                                    <input>${project.build.directory}/build</input>
                                    <destination>${project.build.directory}/installer</destination>
                                    <mainJar>${project.artifactId}-${project.version}.jar</mainJar>
                                    <mainClass>de.tobias.playwall.client.PlayWallMain</mainClass>
                                    <name>PlayWall</name>
                                    <appVersion>${revision-version}</appVersion>
                                    <runtimeImage>${project.build.directory}/PlayWallClient</runtimeImage>
                                    <javaOptions>
                                        <javaOption>--enable-native-access=javafx.graphics</javaOption>
                                    </javaOptions>
                                    <icon>${app.icon}</icon>
                                    <vendor>TheCodeLabs</vendor>

                                    <!-- Windows specific -->
                                    <winMenu>true</winMenu>
                                    <winShortcut>true</winShortcut>
                                    <winMenuGroup>PlayWall</winMenuGroup>
                                    <winUpgradeUuid>${win.upgrade.uuid}</winUpgradeUuid>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>build-helper-maven-plugin</artifactId>
                        <version>3.4.0</version>
                        <executions>
                            <execution>
                                <id>attach-artifact</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>attach-artifact</goal>
                                </goals>
                                <configuration>
                                    <artifacts>
                                        <artifact>
                                            <file>
                                                ${project.build.directory}/installer/PlayWall-${revision-version}.${installer.extension}
                                            </file>
                                            <type>${installer.extension}</type>
                                            <classifier>installer</classifier>
                                        </artifact>
                                    </artifacts>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>