<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.tobias.playwall</groupId>
        <artifactId>PlayWall</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>PlayWallClient</artifactId>

    <properties>
        <surefire.argLineBase>
            --add-opens=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED
            --add-exports=javafx.graphics/com.sun.glass.ui.delegate=ALL-UNNAMED
            --enable-native-access=javafx.graphics
            --enable-native-access=de.thecodelabs.libJfx
            --enable-native-access=de.thecodelabs.libMidi
            -javaagent:${settings.localRepository}/org/mockito/mockito-core/${mockito.version}/mockito-core-${mockito.version}.jar
            -Duser.language=de -Duser.country=DE
            -Djavafx.enablePreview=true -Djavafx.suppressPreviewWarning=true
        </surefire.argLineBase>
        <surefire.argLine>${surefire.argLineBase}</surefire.argLine>
        <failsafe.argLineBase>
            -javaagent:${settings.localRepository}/org/mockito/mockito-core/${mockito.version}/mockito-core-${mockito.version}.jar
        </failsafe.argLineBase>
        <failsafe.argLine>${failsafe.argLineBase}</failsafe.argLine>

        <dmg.file>${project.build.directory}/installer/PlayWall-${revision-version}.dmg</dmg.file>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-web</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-swing</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.controlsfx</groupId>
            <artifactId>controlsfx</artifactId>
            <version>${controlsfx.version}</version>
        </dependency>

        <dependency>
            <groupId>de.thecodelabs</groupId>
            <artifactId>libMidi</artifactId>
        </dependency>

        <dependency>
            <groupId>commons-cli</groupId>
            <artifactId>commons-cli</artifactId>
            <version>${commons-cli.version}</version>
        </dependency>

        <dependency>
            <groupId>io.github.classgraph</groupId>
            <artifactId>classgraph</artifactId>
            <version>${classgraph.version}</version>
        </dependency>

        <!-- Logging -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j-api.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j2-impl</artifactId>
            <version>${log4j2.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j2.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j2.version}</version>
        </dependency>
        <dependency>
            <groupId>org.fusesource.jansi</groupId>
            <artifactId>jansi</artifactId>
            <version>${jansi.version}</version>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>de.thecodelabs</groupId>
            <artifactId>libUtils</artifactId>
        </dependency>
        <dependency>
            <groupId>de.thecodelabs</groupId>
            <artifactId>libJfx</artifactId>
        </dependency>
        <dependency>
            <groupId>de.tobias.playwall</groupId>
            <artifactId>PlayWallCommon</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.scenic-view</groupId>
            <artifactId>scenic-view</artifactId>
            <version>21.0.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.openjfx</groupId>
                    <artifactId>javafx-base</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.openjfx</groupId>
                    <artifactId>javafx-graphics</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.openjfx</groupId>
                    <artifactId>javafx-fxml</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.openjfx</groupId>
                    <artifactId>javafx-controls</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>testfx-core</artifactId>
            <version>${testfx-core.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>testfx-junit5</artifactId>
            <version>${testfx-core.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${mockito.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>openjfx-monocle</artifactId>
            <version>${openjfx-monocle.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility</artifactId>
            <version>${awaitility.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.instancio</groupId>
            <artifactId>instancio-core</artifactId>
            <version>${instancio-core.version}</version>
            <scope>test</scope>
        </dependency>


    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <excludes>
                    <exclude>config/</exclude>
                </excludes>
            </resource>
            <resource>
                <directory>src/main/resources/config</directory>
                <filtering>true</filtering>
                <targetPath>${project.build.outputDirectory}/config</targetPath>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.2.0</version>
                <dependencies>
                    <dependency>
                        <groupId>org.openjdk.nashorn</groupId>
                        <artifactId>nashorn-core</artifactId>
                        <version>15.7</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>generate-scss-colors</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <script language="javascript">
                                    var bytes = java.nio.file.Files.readAllBytes(
                                    java.nio.file.Paths.get("PlayWallClient/src/main/resources/style/colors/ModernColor.json")
                                    );
                                    var content = new java.lang.String(bytes, "UTF-8");
                                    var themes = JSON.parse(content);
                                    var lines = ["$colors: ("];
                                    themes.forEach(function(theme) {
                                    var c = theme.colors;
                                    lines.push("\t " + theme.name + ": (");
                                    lines.push("\t\t hi: " + c.hi + ",");
                                    lines.push("\t\t low: " + c.low + ",");
                                    lines.push("\t\t font: " + c.font + ",");
                                    lines.push("\t\t button: " + c.button + ",");
                                    lines.push("\t\t playbar-bg: " + c.playbar.background + ",");
                                    lines.push("\t\t playbar-track: " + c.playbar.track + ",");
                                    lines.push("\t ),");
                                    });
                                    lines.push(");");
                                    java.nio.file.Files.write(
                                    java.nio.file.Paths.get("PlayWallClient/src/main/sass/components/modern-color.scss"),
                                    lines.join("\n").getBytes("UTF-8")
                                    );
                                    self.log("modern-color.scss generated");
                                </script>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>io.github.cleydyr</groupId>
                <artifactId>dart-sass-maven-plugin</artifactId>
                <version>${dart-sass-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>generate-css-using-sass</id>
                        <goals>
                            <goal>compile-sass</goal>
                        </goals>
                        <phase>generate-resources</phase>
                    </execution>
                </executions>
                <configuration>
                    <!-- use a fixed version of dart-saas to ensure reproducible builds -->
                    <version>${dart-sass.version}</version>
                    <inputFolder>src/main/sass</inputFolder>
                    <outputFolder>target/classes/style</outputFolder>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${maven-jar-plugin.version}</version>
                <configuration>
                    <outputDirectory>${project.build.directory}/build</outputDirectory>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>${surefire.argLine}</argLine>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${maven-failsafe-plugin.version}</version>
                <configuration>
                    <argLine>${failsafe.argLine}</argLine>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>headless-ui-tests</id>
            <properties>
                <surefire.argLine>
                    ${surefire.argLineBase}
                    --add-opens=javafx.graphics/com.sun.javafx.util=ALL-UNNAMED
                    --add-opens=javafx.base/com.sun.javafx.logging=ALL-UNNAMED
                    -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw
                </surefire.argLine>
            </properties>
        </profile>

        <profile>
            <id>code-coverage</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <argLine>${surefire.argLine} ${surefire.argLineJacoco}</argLine>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <configuration>
                            <argLine>${failsafe.argLine} ${failsafe.argLineJacoco}</argLine>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>windows</id>
            <activation>
                <os>
                    <family>Windows</family>
                </os>
            </activation>
            <properties>
                <app.icon>src/main/resources/de/tobias/playwall/client/logo/icon.ico</app.icon>
                <installer.type>EXE</installer.type>
                <installer.extension>exe</installer.extension>
            </properties>
        </profile>

        <profile>
            <id>linux</id>
            <activation>
                <os>
                    <family>unix</family>
                    <name>Linux</name>
                </os>
            </activation>
            <properties>
                <app.icon>src/main/resources/de/tobias/playwall/client/logo/icon_small.png</app.icon>
                <installer.type>APP_IMAGE</installer.type>
                <installer.extension>${os.arch}.tar.gz</installer.extension>
            </properties>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                <id>archive-app-image</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target>
                                        <exec executable="bash" dir="${project.build.directory}"
                                              failonerror="true">
                                            <arg value="-c"/>
                                            <arg value="if [ -d installer/PlayWall ]; then cd installer &amp;&amp; tar -czf 'PlayWall-${revision-version}.${os.arch}.tar.gz' PlayWall; else echo 'Skipping app-image archive: target/installer/PlayWall not found (package-executables not active)'; fi"/>
                                        </exec>
                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!-- macOS Build -->
        <profile>
            <id>mac</id>
            <activation>
                <os>
                    <family>mac</family>
                </os>
            </activation>
            <properties>
                <app.icon>src/main/resources/de/tobias/playwall/client/logo/icon.icns</app.icon>
                <installer.type>DMG</installer.type>
                <installer.extension>dmg</installer.extension>
            </properties>
        </profile>

        <profile>
            <id>package-executables</id>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.openjfx</groupId>
                        <artifactId>javafx-maven-plugin</artifactId>
                        <version>${javafx-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>create-runtime-image</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>jlink</goal>
                                </goals>
                                <configuration>
                                    <mainClass>de.tobias.playwall.client.PlayWallMain</mainClass>
                                    <stripDebug>true</stripDebug>
                                    <compress>2</compress>
                                    <noHeaderFiles>true</noHeaderFiles>
                                    <noManPages>true</noManPages>
                                    <launcher>PlayWall</launcher>
                                    <jlinkImageName>PlayWallClient</jlinkImageName>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                        <version>${jpackage-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>build-executable</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>jpackage</goal>
                                </goals>
                                <configuration>
                                    <type>${installer.type}</type>
                                    <input>${project.build.directory}/build</input>
                                    <destination>${project.build.directory}/installer</destination>
                                    <mainJar>${project.artifactId}-${project.version}.jar</mainJar>
                                    <mainClass>de.tobias.playwall.client.PlayWallMain</mainClass>
                                    <name>PlayWall</name>
                                    <appVersion>${revision-version}</appVersion>
                                    <runtimeImage>${project.build.directory}/PlayWallClient</runtimeImage>
                                    <javaOptions>
                                        <javaOption>--enable-native-access=javafx.graphics</javaOption>
                                        <javaOption>--enable-native-access=de.thecodelabs.libJfx</javaOption>
                                        <javaOption>-Djavafx.enablePreview=true</javaOption>
                                        <javaOption>-Djavafx.suppressPreviewWarning=true</javaOption>
                                    </javaOptions>
                                    <icon>${app.icon}</icon>
                                    <vendor>TheCodeLabs</vendor>

                                    <!-- Mac specific -->
                                    <macAppCategory>public.app-category.music</macAppCategory>
                                    <macPackageIdentifier>de.tobias.playwall</macPackageIdentifier>
                                    <macSign>true</macSign>
                                    <macSigningKeyUserName>${mac.sign.identity}</macSigningKeyUserName>

                                    <!-- Windows specific -->
                                    <winMenu>true</winMenu>
                                    <winShortcut>true</winShortcut>
                                    <winMenuGroup>PlayWall</winMenuGroup>
                                    <winUpgradeUuid>A4185328-E7A2-43E7-BD7A-92F80294E483</winUpgradeUuid>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>build-helper-maven-plugin</artifactId>
                        <version>3.6.1</version>
                        <executions>
                            <execution>
                                <id>attach-artifact</id>
                                <phase>install</phase>
                                <goals>
                                    <goal>attach-artifact</goal>
                                </goals>
                                <configuration>
                                    <artifacts>
                                        <artifact>
                                            <file>
                                                ${project.build.directory}/installer/PlayWall-${revision-version}.${installer.extension}
                                            </file>
                                            <type>${installer.extension}</type>
                                            <classifier>installer</classifier>
                                        </artifact>
                                    </artifacts>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>sign-dmg</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>sign-dmg</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>codesign</executable>
                                    <arguments>
                                        <argument>--force</argument>
                                        <argument>--keychain</argument>
                                        <argument>${mac.sign.keychain}</argument>
                                        <argument>--sign</argument>
                                        <argument>${mac.sign.identity}</argument>
                                        <argument>${dmg.file}</argument>
                                    </arguments>
                                </configuration>
                            </execution>

                            <!-- NOTARIZE -->
                            <execution>
                                <id>notarize-dmg</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>xcrun</executable>
                                    <arguments>
                                        <argument>notarytool</argument>
                                        <argument>submit</argument>
                                        <argument>${dmg.file}</argument>
                                        <argument>--key</argument>
                                        <argument>${mac.notary.key}</argument>
                                        <argument>--key-id</argument>
                                        <argument>${mac.notary.key.id}</argument>
                                        <argument>--issuer</argument>
                                        <argument>${mac.notary.issuer}</argument>
                                        <argument>--wait</argument>
                                    </arguments>
                                </configuration>
                            </execution>

                            <!-- STAPLE -->
                            <execution>
                                <id>staple-dmg</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>xcrun</executable>
                                    <arguments>
                                        <argument>stapler</argument>
                                        <argument>staple</argument>
                                        <argument>${dmg.file}</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>