<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.tobias.playwall</groupId>
        <artifactId>PlayWall</artifactId>
        <version>8.0.0</version>
    </parent>

    <artifactId>PlayWallClient</artifactId>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <junit.version>5.10.2</junit.version>
        <javafx.version>25</javafx.version>
        <controlsfx.version>11.2.1</controlsfx.version>

        <sass-maven-plugin.version>3.7.2</sass-maven-plugin.version>
        <javafx-maven-plugin.version>0.0.8</javafx-maven-plugin.version>
        <jpackage-maven-plugin.version>1.7.1</jpackage-maven-plugin.version>
        <maven-jar-plugin.version>3.3.0</maven-jar-plugin.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-swing</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.controlsfx</groupId>
            <artifactId>controlsfx</artifactId>
            <version>${controlsfx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.github.classgraph</groupId>
            <artifactId>classgraph</artifactId>
            <version>4.8.179</version>
        </dependency>

        <dependency>
            <groupId>de.thecodelabs</groupId>
            <artifactId>libUtils</artifactId>
        </dependency>
        <dependency>
            <groupId>de.thecodelabs</groupId>
            <artifactId>libLogger</artifactId>
        </dependency>
        <dependency>
            <groupId>de.thecodelabs</groupId>
            <artifactId>libJfx</artifactId>
        </dependency>
        <dependency>
            <groupId>de.tobias.playwall</groupId>
            <artifactId>PlayWallCommon</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <excludes>
                    <exclude>config/</exclude>
                </excludes>
            </resource>
            <resource>
                <directory>src/main/resources/config</directory>
                <filtering>true</filtering>
                <targetPath>${project.build.outputDirectory}/config</targetPath>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>nl.geodienstencentrum.maven</groupId>
                <artifactId>sass-maven-plugin</artifactId>
                <version>${sass-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>translate-css</id>
                        <goals>
                            <goal>update-stylesheets</goal>
                        </goals>
                        <phase>generate-resources</phase>
                        <configuration>
                            <destination>target/classes/style</destination>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${maven-jar-plugin.version}</version>
                <configuration>
                    <outputDirectory>${project.build.directory}/build</outputDirectory>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>windows</id>
            <activation>
                <os>
                    <family>Windows</family>
                </os>
            </activation>
            <properties>
                <app.icon>src/main/resources/de/tobias/playwall/client/logo/icon.ico</app.icon>
            </properties>
        </profile>

        <!-- macOS Build -->
        <profile>
            <id>mac</id>
            <activation>
                <os>
                    <family>mac</family>
                </os>
            </activation>
            <properties>
                <app.icon>src/main/resources/de/tobias/playwall/client/logo/icon.icns</app.icon>
            </properties>
        </profile>

        <profile>
            <id>package-executables</id>

            <dependencies>
                <dependency>
                    <groupId>org.fusesource.jansi</groupId>
                    <artifactId>jansi</artifactId>
                    <version>1.18-module</version>
                </dependency>
                <dependency>
                    <groupId>net.java.dev.jna</groupId>
                    <artifactId>jna</artifactId>
                    <version>5.5.0-module</version>
                </dependency>
                <dependency>
                    <groupId>net.java.dev.jna</groupId>
                    <artifactId>jna-platform</artifactId>
                    <version>5.5.0-module</version>
                </dependency>
            </dependencies>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.openjfx</groupId>
                        <artifactId>javafx-maven-plugin</artifactId>
                        <version>${javafx-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>create-runtime-image</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>jlink</goal>
                                </goals>
                                <configuration>
                                    <mainClass>de.tobias.playwall.client.PlayWallMain</mainClass>
                                    <stripDebug>true</stripDebug>
                                    <compress>2</compress>
                                    <noHeaderFiles>true</noHeaderFiles>
                                    <noManPages>true</noManPages>
                                    <launcher>PlayWall</launcher>
                                    <jlinkImageName>PlayWallClient</jlinkImageName>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                        <version>${jpackage-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>build-executable</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>jpackage</goal>
                                </goals>
                                <configuration>
                                    <input>${project.build.directory}/build</input>
                                    <destination>${project.build.directory}/installer</destination>
                                    <mainJar>${project.artifactId}-${project.version}.jar</mainJar>
                                    <mainClass>de.tobias.playwall.client.PlayWallMain</mainClass>
                                    <name>PlayWall</name>
                                    <appVersion>${project.version}</appVersion>
                                    <runtimeImage>${project.build.directory}/PlayWallClient</runtimeImage>
                                    <javaOptions>
                                        <javaOption>--enable-native-access=javafx.graphics</javaOption>
                                    </javaOptions>
                                    <icon>${app.icon}</icon>
                                    <vendor>TheCodeLabs</vendor>

                                    <!-- Windows specific -->
                                    <winMenu>true</winMenu>
                                    <winShortcut>true</winShortcut>
                                    <winMenuGroup>PlayWall</winMenuGroup>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>