<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>de.tobias.playwall</groupId>
        <artifactId>PlayWall</artifactId>
        <version>8.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>coverage</artifactId>

    <dependencies>
        <dependency>
            <groupId>de.tobias.playwall</groupId>
            <artifactId>PlayWallClient</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.tobias.playwall</groupId>
            <artifactId>PlayWallCommon</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.tobias.playwall</groupId>
            <artifactId>PlayWallServer</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.tobias.playwall</groupId>
            <artifactId>PlayWallServerCommon</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>aggregate-reports-all</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report-aggregate</goal>
                        </goals>
                        <configuration>
                            <title>PlayWall Code Coverage</title>
                            <outputDirectory>${project.reporting.outputDirectory}/jacoco-aggregate</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>